version: '2'
services:
  discourse:
    image: adab1ts/discourse:1.0.0-dev
    build:
      context: .
      dockerfile: config/docker/Dockerfile
      args:
        - APP_HOME=/srv/www/discourse
    volumes:
      - .:/srv/www/discourse
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
      - "3080:1080"
    depends_on:
      - postgres
      - redis
    command: bundle exec rails server -p 3000 -b '0.0.0.0'

  postgres:
    image: postgres:9.6
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

  redis:
    image: redis:2.8
